/**
 * @fileoverview
 * @enhanceable
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.proxy.CognitoIdentity', null, global);
goog.exportSymbol('proto.proxy.LambdaContext', null, global);
goog.exportSymbol('proto.proxy.ProxyRequest', null, global);
goog.exportSymbol('proto.proxy.ProxyResponse', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.proxy.CognitoIdentity = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.proxy.CognitoIdentity, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.proxy.CognitoIdentity.displayName = 'proto.proxy.CognitoIdentity';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.proxy.CognitoIdentity.prototype.toObject = function(opt_includeInstance) {
  return proto.proxy.CognitoIdentity.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.proxy.CognitoIdentity} msg The msg instance to transform.
 * @return {!Object}
 */
proto.proxy.CognitoIdentity.toObject = function(includeInstance, msg) {
  var f, obj = {
    cognitoIdentityId: jspb.Message.getFieldWithDefault(msg, 1, ""),
    cognitoIdentityPoolId: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.proxy.CognitoIdentity}
 */
proto.proxy.CognitoIdentity.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.proxy.CognitoIdentity;
  return proto.proxy.CognitoIdentity.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.proxy.CognitoIdentity} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.proxy.CognitoIdentity}
 */
proto.proxy.CognitoIdentity.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setCognitoIdentityId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setCognitoIdentityPoolId(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.proxy.CognitoIdentity.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.proxy.CognitoIdentity.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.proxy.CognitoIdentity} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.proxy.CognitoIdentity.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getCognitoIdentityId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getCognitoIdentityPoolId();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional string cognito_identity_id = 1;
 * @return {string}
 */
proto.proxy.CognitoIdentity.prototype.getCognitoIdentityId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.proxy.CognitoIdentity.prototype.setCognitoIdentityId = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional string cognito_identity_pool_id = 2;
 * @return {string}
 */
proto.proxy.CognitoIdentity.prototype.getCognitoIdentityPoolId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.proxy.CognitoIdentity.prototype.setCognitoIdentityPoolId = function(value) {
  jspb.Message.setField(this, 2, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.proxy.LambdaContext = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.proxy.LambdaContext, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.proxy.LambdaContext.displayName = 'proto.proxy.LambdaContext';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.proxy.LambdaContext.prototype.toObject = function(opt_includeInstance) {
  return proto.proxy.LambdaContext.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.proxy.LambdaContext} msg The msg instance to transform.
 * @return {!Object}
 */
proto.proxy.LambdaContext.toObject = function(includeInstance, msg) {
  var f, obj = {
    functionName: jspb.Message.getFieldWithDefault(msg, 1, ""),
    functionVersion: jspb.Message.getFieldWithDefault(msg, 2, ""),
    invokedFunctionArn: jspb.Message.getFieldWithDefault(msg, 3, ""),
    memoryLimitInMb: jspb.Message.getFieldWithDefault(msg, 4, ""),
    awsRequestId: jspb.Message.getFieldWithDefault(msg, 5, ""),
    logGroupName: jspb.Message.getFieldWithDefault(msg, 6, ""),
    logStreamName: jspb.Message.getFieldWithDefault(msg, 7, ""),
    identity: (f = msg.getIdentity()) && proto.proxy.CognitoIdentity.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.proxy.LambdaContext}
 */
proto.proxy.LambdaContext.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.proxy.LambdaContext;
  return proto.proxy.LambdaContext.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.proxy.LambdaContext} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.proxy.LambdaContext}
 */
proto.proxy.LambdaContext.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setFunctionName(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setFunctionVersion(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setInvokedFunctionArn(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setMemoryLimitInMb(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setAwsRequestId(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setLogGroupName(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setLogStreamName(value);
      break;
    case 8:
      var value = new proto.proxy.CognitoIdentity;
      reader.readMessage(value,proto.proxy.CognitoIdentity.deserializeBinaryFromReader);
      msg.setIdentity(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.proxy.LambdaContext.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.proxy.LambdaContext.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.proxy.LambdaContext} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.proxy.LambdaContext.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getFunctionName();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getFunctionVersion();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getInvokedFunctionArn();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getMemoryLimitInMb();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getAwsRequestId();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getLogGroupName();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getLogStreamName();
  if (f.length > 0) {
    writer.writeString(
      7,
      f
    );
  }
  f = message.getIdentity();
  if (f != null) {
    writer.writeMessage(
      8,
      f,
      proto.proxy.CognitoIdentity.serializeBinaryToWriter
    );
  }
};


/**
 * optional string function_name = 1;
 * @return {string}
 */
proto.proxy.LambdaContext.prototype.getFunctionName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.proxy.LambdaContext.prototype.setFunctionName = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional string function_version = 2;
 * @return {string}
 */
proto.proxy.LambdaContext.prototype.getFunctionVersion = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.proxy.LambdaContext.prototype.setFunctionVersion = function(value) {
  jspb.Message.setField(this, 2, value);
};


/**
 * optional string invoked_function_arn = 3;
 * @return {string}
 */
proto.proxy.LambdaContext.prototype.getInvokedFunctionArn = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/** @param {string} value */
proto.proxy.LambdaContext.prototype.setInvokedFunctionArn = function(value) {
  jspb.Message.setField(this, 3, value);
};


/**
 * optional string memory_limit_in_mb = 4;
 * @return {string}
 */
proto.proxy.LambdaContext.prototype.getMemoryLimitInMb = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/** @param {string} value */
proto.proxy.LambdaContext.prototype.setMemoryLimitInMb = function(value) {
  jspb.Message.setField(this, 4, value);
};


/**
 * optional string aws_request_id = 5;
 * @return {string}
 */
proto.proxy.LambdaContext.prototype.getAwsRequestId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/** @param {string} value */
proto.proxy.LambdaContext.prototype.setAwsRequestId = function(value) {
  jspb.Message.setField(this, 5, value);
};


/**
 * optional string log_group_name = 6;
 * @return {string}
 */
proto.proxy.LambdaContext.prototype.getLogGroupName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/** @param {string} value */
proto.proxy.LambdaContext.prototype.setLogGroupName = function(value) {
  jspb.Message.setField(this, 6, value);
};


/**
 * optional string log_stream_name = 7;
 * @return {string}
 */
proto.proxy.LambdaContext.prototype.getLogStreamName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/** @param {string} value */
proto.proxy.LambdaContext.prototype.setLogStreamName = function(value) {
  jspb.Message.setField(this, 7, value);
};


/**
 * optional CognitoIdentity identity = 8;
 * @return {?proto.proxy.CognitoIdentity}
 */
proto.proxy.LambdaContext.prototype.getIdentity = function() {
  return /** @type{?proto.proxy.CognitoIdentity} */ (
    jspb.Message.getWrapperField(this, proto.proxy.CognitoIdentity, 8));
};


/** @param {?proto.proxy.CognitoIdentity|undefined} value */
proto.proxy.LambdaContext.prototype.setIdentity = function(value) {
  jspb.Message.setWrapperField(this, 8, value);
};


proto.proxy.LambdaContext.prototype.clearIdentity = function() {
  this.setIdentity(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.proxy.LambdaContext.prototype.hasIdentity = function() {
  return jspb.Message.getField(this, 8) != null;
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.proxy.ProxyRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.proxy.ProxyRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.proxy.ProxyRequest.displayName = 'proto.proxy.ProxyRequest';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.proxy.ProxyRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.proxy.ProxyRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.proxy.ProxyRequest} msg The msg instance to transform.
 * @return {!Object}
 */
proto.proxy.ProxyRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    context: (f = msg.getContext()) && proto.proxy.LambdaContext.toObject(includeInstance, f),
    event: msg.getEvent_asB64()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.proxy.ProxyRequest}
 */
proto.proxy.ProxyRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.proxy.ProxyRequest;
  return proto.proxy.ProxyRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.proxy.ProxyRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.proxy.ProxyRequest}
 */
proto.proxy.ProxyRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.proxy.LambdaContext;
      reader.readMessage(value,proto.proxy.LambdaContext.deserializeBinaryFromReader);
      msg.setContext(value);
      break;
    case 2:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setEvent(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.proxy.ProxyRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.proxy.ProxyRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.proxy.ProxyRequest} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.proxy.ProxyRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getContext();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.proxy.LambdaContext.serializeBinaryToWriter
    );
  }
  f = message.getEvent_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      2,
      f
    );
  }
};


/**
 * optional LambdaContext context = 1;
 * @return {?proto.proxy.LambdaContext}
 */
proto.proxy.ProxyRequest.prototype.getContext = function() {
  return /** @type{?proto.proxy.LambdaContext} */ (
    jspb.Message.getWrapperField(this, proto.proxy.LambdaContext, 1));
};


/** @param {?proto.proxy.LambdaContext|undefined} value */
proto.proxy.ProxyRequest.prototype.setContext = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


proto.proxy.ProxyRequest.prototype.clearContext = function() {
  this.setContext(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.proxy.ProxyRequest.prototype.hasContext = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional bytes event = 2;
 * @return {!(string|Uint8Array)}
 */
proto.proxy.ProxyRequest.prototype.getEvent = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * optional bytes event = 2;
 * This is a type-conversion wrapper around `getEvent()`
 * @return {string}
 */
proto.proxy.ProxyRequest.prototype.getEvent_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getEvent()));
};


/**
 * optional bytes event = 2;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getEvent()`
 * @return {!Uint8Array}
 */
proto.proxy.ProxyRequest.prototype.getEvent_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getEvent()));
};


/** @param {!(string|Uint8Array)} value */
proto.proxy.ProxyRequest.prototype.setEvent = function(value) {
  jspb.Message.setField(this, 2, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.proxy.ProxyResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.proxy.ProxyResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.proxy.ProxyResponse.displayName = 'proto.proxy.ProxyResponse';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.proxy.ProxyResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.proxy.ProxyResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.proxy.ProxyResponse} msg The msg instance to transform.
 * @return {!Object}
 */
proto.proxy.ProxyResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    body: msg.getBody_asB64()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.proxy.ProxyResponse}
 */
proto.proxy.ProxyResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.proxy.ProxyResponse;
  return proto.proxy.ProxyResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.proxy.ProxyResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.proxy.ProxyResponse}
 */
proto.proxy.ProxyResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setBody(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.proxy.ProxyResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.proxy.ProxyResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.proxy.ProxyResponse} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.proxy.ProxyResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getBody_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      1,
      f
    );
  }
};


/**
 * optional bytes body = 1;
 * @return {!(string|Uint8Array)}
 */
proto.proxy.ProxyResponse.prototype.getBody = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * optional bytes body = 1;
 * This is a type-conversion wrapper around `getBody()`
 * @return {string}
 */
proto.proxy.ProxyResponse.prototype.getBody_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getBody()));
};


/**
 * optional bytes body = 1;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getBody()`
 * @return {!Uint8Array}
 */
proto.proxy.ProxyResponse.prototype.getBody_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getBody()));
};


/** @param {!(string|Uint8Array)} value */
proto.proxy.ProxyResponse.prototype.setBody = function(value) {
  jspb.Message.setField(this, 1, value);
};


goog.object.extend(exports, proto.proxy);
