# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proxy.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proxy.proto',
  package='proxy',
  syntax='proto3',
  serialized_pb=_b('\n\x0bproxy.proto\x12\x05proxy\"K\n\x0f\x43ognitoIdentity\x12\x19\n\x11\x43ognitoIdentityId\x18\x01 \x01(\t\x12\x1d\n\x15\x43ognitoIdentityPoolId\x18\x02 \x01(\t\"\xf2\x01\n\rLambdaContext\x12\x14\n\x0c\x46unctionName\x18\x01 \x01(\t\x12\x17\n\x0f\x46unctionVersion\x18\x02 \x01(\t\x12\x1a\n\x12InvokedFunctionARN\x18\x03 \x01(\t\x12\x17\n\x0fMemoryLimitInMB\x18\x04 \x01(\t\x12\x14\n\x0c\x41WSRequestId\x18\x05 \x01(\t\x12\x14\n\x0cLogGroupName\x18\x06 \x01(\t\x12\x15\n\rLogStreamName\x18\x07 \x01(\t\x12\x10\n\x08InvokeId\x18\x08 \x01(\t\x12(\n\x08Identity\x18\t \x01(\x0b\x32\x16.proxy.CognitoIdentity\"D\n\x0cProxyRequest\x12%\n\x07\x43ontext\x18\x01 \x01(\x0b\x32\x14.proxy.LambdaContext\x12\r\n\x05\x45vent\x18\x02 \x01(\x0c\"\x1d\n\rProxyResponse\x12\x0c\n\x04\x42ody\x18\x01 \x01(\x0c\x62\x06proto3')
)




_COGNITOIDENTITY = _descriptor.Descriptor(
  name='CognitoIdentity',
  full_name='proxy.CognitoIdentity',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='CognitoIdentityId', full_name='proxy.CognitoIdentity.CognitoIdentityId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='CognitoIdentityPoolId', full_name='proxy.CognitoIdentity.CognitoIdentityPoolId', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=97,
)


_LAMBDACONTEXT = _descriptor.Descriptor(
  name='LambdaContext',
  full_name='proxy.LambdaContext',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='FunctionName', full_name='proxy.LambdaContext.FunctionName', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='FunctionVersion', full_name='proxy.LambdaContext.FunctionVersion', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='InvokedFunctionARN', full_name='proxy.LambdaContext.InvokedFunctionARN', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='MemoryLimitInMB', full_name='proxy.LambdaContext.MemoryLimitInMB', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='AWSRequestId', full_name='proxy.LambdaContext.AWSRequestId', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='LogGroupName', full_name='proxy.LambdaContext.LogGroupName', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='LogStreamName', full_name='proxy.LambdaContext.LogStreamName', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='InvokeId', full_name='proxy.LambdaContext.InvokeId', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Identity', full_name='proxy.LambdaContext.Identity', index=8,
      number=9, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=100,
  serialized_end=342,
)


_PROXYREQUEST = _descriptor.Descriptor(
  name='ProxyRequest',
  full_name='proxy.ProxyRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Context', full_name='proxy.ProxyRequest.Context', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Event', full_name='proxy.ProxyRequest.Event', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=344,
  serialized_end=412,
)


_PROXYRESPONSE = _descriptor.Descriptor(
  name='ProxyResponse',
  full_name='proxy.ProxyResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Body', full_name='proxy.ProxyResponse.Body', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=414,
  serialized_end=443,
)

_LAMBDACONTEXT.fields_by_name['Identity'].message_type = _COGNITOIDENTITY
_PROXYREQUEST.fields_by_name['Context'].message_type = _LAMBDACONTEXT
DESCRIPTOR.message_types_by_name['CognitoIdentity'] = _COGNITOIDENTITY
DESCRIPTOR.message_types_by_name['LambdaContext'] = _LAMBDACONTEXT
DESCRIPTOR.message_types_by_name['ProxyRequest'] = _PROXYREQUEST
DESCRIPTOR.message_types_by_name['ProxyResponse'] = _PROXYRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CognitoIdentity = _reflection.GeneratedProtocolMessageType('CognitoIdentity', (_message.Message,), dict(
  DESCRIPTOR = _COGNITOIDENTITY,
  __module__ = 'proxy_pb2'
  # @@protoc_insertion_point(class_scope:proxy.CognitoIdentity)
  ))
_sym_db.RegisterMessage(CognitoIdentity)

LambdaContext = _reflection.GeneratedProtocolMessageType('LambdaContext', (_message.Message,), dict(
  DESCRIPTOR = _LAMBDACONTEXT,
  __module__ = 'proxy_pb2'
  # @@protoc_insertion_point(class_scope:proxy.LambdaContext)
  ))
_sym_db.RegisterMessage(LambdaContext)

ProxyRequest = _reflection.GeneratedProtocolMessageType('ProxyRequest', (_message.Message,), dict(
  DESCRIPTOR = _PROXYREQUEST,
  __module__ = 'proxy_pb2'
  # @@protoc_insertion_point(class_scope:proxy.ProxyRequest)
  ))
_sym_db.RegisterMessage(ProxyRequest)

ProxyResponse = _reflection.GeneratedProtocolMessageType('ProxyResponse', (_message.Message,), dict(
  DESCRIPTOR = _PROXYRESPONSE,
  __module__ = 'proxy_pb2'
  # @@protoc_insertion_point(class_scope:proxy.ProxyResponse)
  ))
_sym_db.RegisterMessage(ProxyResponse)


# @@protoc_insertion_point(module_scope)
