/**
 * @fileoverview
 * @enhanceable
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.proxy.CognitoIdentity', null, global);
goog.exportSymbol('proto.proxy.LambdaContext', null, global);
goog.exportSymbol('proto.proxy.ProxyRequest', null, global);
goog.exportSymbol('proto.proxy.ProxyResponse', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.proxy.CognitoIdentity = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.proxy.CognitoIdentity, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.proxy.CognitoIdentity.displayName = 'proto.proxy.CognitoIdentity';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.proxy.CognitoIdentity.prototype.toObject = function(opt_includeInstance) {
  return proto.proxy.CognitoIdentity.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.proxy.CognitoIdentity} msg The msg instance to transform.
 * @return {!Object}
 */
proto.proxy.CognitoIdentity.toObject = function(includeInstance, msg) {
  var f, obj = {
    cognitoidentityid: jspb.Message.getFieldWithDefault(msg, 1, ""),
    cognitoidentitypoolid: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.proxy.CognitoIdentity}
 */
proto.proxy.CognitoIdentity.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.proxy.CognitoIdentity;
  return proto.proxy.CognitoIdentity.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.proxy.CognitoIdentity} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.proxy.CognitoIdentity}
 */
proto.proxy.CognitoIdentity.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setCognitoidentityid(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setCognitoidentitypoolid(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.proxy.CognitoIdentity.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.proxy.CognitoIdentity.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.proxy.CognitoIdentity} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.proxy.CognitoIdentity.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getCognitoidentityid();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getCognitoidentitypoolid();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional string CognitoIdentityId = 1;
 * @return {string}
 */
proto.proxy.CognitoIdentity.prototype.getCognitoidentityid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.proxy.CognitoIdentity.prototype.setCognitoidentityid = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional string CognitoIdentityPoolId = 2;
 * @return {string}
 */
proto.proxy.CognitoIdentity.prototype.getCognitoidentitypoolid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.proxy.CognitoIdentity.prototype.setCognitoidentitypoolid = function(value) {
  jspb.Message.setField(this, 2, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.proxy.LambdaContext = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.proxy.LambdaContext, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.proxy.LambdaContext.displayName = 'proto.proxy.LambdaContext';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.proxy.LambdaContext.prototype.toObject = function(opt_includeInstance) {
  return proto.proxy.LambdaContext.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.proxy.LambdaContext} msg The msg instance to transform.
 * @return {!Object}
 */
proto.proxy.LambdaContext.toObject = function(includeInstance, msg) {
  var f, obj = {
    functionname: jspb.Message.getFieldWithDefault(msg, 1, ""),
    functionversion: jspb.Message.getFieldWithDefault(msg, 2, ""),
    invokedfunctionarn: jspb.Message.getFieldWithDefault(msg, 3, ""),
    memorylimitinmb: jspb.Message.getFieldWithDefault(msg, 4, ""),
    awsrequestid: jspb.Message.getFieldWithDefault(msg, 5, ""),
    loggroupname: jspb.Message.getFieldWithDefault(msg, 6, ""),
    logstreamname: jspb.Message.getFieldWithDefault(msg, 7, ""),
    invokeid: jspb.Message.getFieldWithDefault(msg, 8, ""),
    identity: (f = msg.getIdentity()) && proto.proxy.CognitoIdentity.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.proxy.LambdaContext}
 */
proto.proxy.LambdaContext.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.proxy.LambdaContext;
  return proto.proxy.LambdaContext.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.proxy.LambdaContext} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.proxy.LambdaContext}
 */
proto.proxy.LambdaContext.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setFunctionname(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setFunctionversion(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setInvokedfunctionarn(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setMemorylimitinmb(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setAwsrequestid(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setLoggroupname(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setLogstreamname(value);
      break;
    case 8:
      var value = /** @type {string} */ (reader.readString());
      msg.setInvokeid(value);
      break;
    case 9:
      var value = new proto.proxy.CognitoIdentity;
      reader.readMessage(value,proto.proxy.CognitoIdentity.deserializeBinaryFromReader);
      msg.setIdentity(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.proxy.LambdaContext.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.proxy.LambdaContext.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.proxy.LambdaContext} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.proxy.LambdaContext.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getFunctionname();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getFunctionversion();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getInvokedfunctionarn();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getMemorylimitinmb();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getAwsrequestid();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getLoggroupname();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getLogstreamname();
  if (f.length > 0) {
    writer.writeString(
      7,
      f
    );
  }
  f = message.getInvokeid();
  if (f.length > 0) {
    writer.writeString(
      8,
      f
    );
  }
  f = message.getIdentity();
  if (f != null) {
    writer.writeMessage(
      9,
      f,
      proto.proxy.CognitoIdentity.serializeBinaryToWriter
    );
  }
};


/**
 * optional string FunctionName = 1;
 * @return {string}
 */
proto.proxy.LambdaContext.prototype.getFunctionname = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.proxy.LambdaContext.prototype.setFunctionname = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional string FunctionVersion = 2;
 * @return {string}
 */
proto.proxy.LambdaContext.prototype.getFunctionversion = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.proxy.LambdaContext.prototype.setFunctionversion = function(value) {
  jspb.Message.setField(this, 2, value);
};


/**
 * optional string InvokedFunctionARN = 3;
 * @return {string}
 */
proto.proxy.LambdaContext.prototype.getInvokedfunctionarn = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/** @param {string} value */
proto.proxy.LambdaContext.prototype.setInvokedfunctionarn = function(value) {
  jspb.Message.setField(this, 3, value);
};


/**
 * optional string MemoryLimitInMB = 4;
 * @return {string}
 */
proto.proxy.LambdaContext.prototype.getMemorylimitinmb = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/** @param {string} value */
proto.proxy.LambdaContext.prototype.setMemorylimitinmb = function(value) {
  jspb.Message.setField(this, 4, value);
};


/**
 * optional string AWSRequestId = 5;
 * @return {string}
 */
proto.proxy.LambdaContext.prototype.getAwsrequestid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/** @param {string} value */
proto.proxy.LambdaContext.prototype.setAwsrequestid = function(value) {
  jspb.Message.setField(this, 5, value);
};


/**
 * optional string LogGroupName = 6;
 * @return {string}
 */
proto.proxy.LambdaContext.prototype.getLoggroupname = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/** @param {string} value */
proto.proxy.LambdaContext.prototype.setLoggroupname = function(value) {
  jspb.Message.setField(this, 6, value);
};


/**
 * optional string LogStreamName = 7;
 * @return {string}
 */
proto.proxy.LambdaContext.prototype.getLogstreamname = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/** @param {string} value */
proto.proxy.LambdaContext.prototype.setLogstreamname = function(value) {
  jspb.Message.setField(this, 7, value);
};


/**
 * optional string InvokeId = 8;
 * @return {string}
 */
proto.proxy.LambdaContext.prototype.getInvokeid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 8, ""));
};


/** @param {string} value */
proto.proxy.LambdaContext.prototype.setInvokeid = function(value) {
  jspb.Message.setField(this, 8, value);
};


/**
 * optional CognitoIdentity Identity = 9;
 * @return {?proto.proxy.CognitoIdentity}
 */
proto.proxy.LambdaContext.prototype.getIdentity = function() {
  return /** @type{?proto.proxy.CognitoIdentity} */ (
    jspb.Message.getWrapperField(this, proto.proxy.CognitoIdentity, 9));
};


/** @param {?proto.proxy.CognitoIdentity|undefined} value */
proto.proxy.LambdaContext.prototype.setIdentity = function(value) {
  jspb.Message.setWrapperField(this, 9, value);
};


proto.proxy.LambdaContext.prototype.clearIdentity = function() {
  this.setIdentity(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.proxy.LambdaContext.prototype.hasIdentity = function() {
  return jspb.Message.getField(this, 9) != null;
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.proxy.ProxyRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.proxy.ProxyRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.proxy.ProxyRequest.displayName = 'proto.proxy.ProxyRequest';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.proxy.ProxyRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.proxy.ProxyRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.proxy.ProxyRequest} msg The msg instance to transform.
 * @return {!Object}
 */
proto.proxy.ProxyRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    context: (f = msg.getContext()) && proto.proxy.LambdaContext.toObject(includeInstance, f),
    event: msg.getEvent_asB64()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.proxy.ProxyRequest}
 */
proto.proxy.ProxyRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.proxy.ProxyRequest;
  return proto.proxy.ProxyRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.proxy.ProxyRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.proxy.ProxyRequest}
 */
proto.proxy.ProxyRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.proxy.LambdaContext;
      reader.readMessage(value,proto.proxy.LambdaContext.deserializeBinaryFromReader);
      msg.setContext(value);
      break;
    case 2:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setEvent(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.proxy.ProxyRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.proxy.ProxyRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.proxy.ProxyRequest} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.proxy.ProxyRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getContext();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.proxy.LambdaContext.serializeBinaryToWriter
    );
  }
  f = message.getEvent_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      2,
      f
    );
  }
};


/**
 * optional LambdaContext Context = 1;
 * @return {?proto.proxy.LambdaContext}
 */
proto.proxy.ProxyRequest.prototype.getContext = function() {
  return /** @type{?proto.proxy.LambdaContext} */ (
    jspb.Message.getWrapperField(this, proto.proxy.LambdaContext, 1));
};


/** @param {?proto.proxy.LambdaContext|undefined} value */
proto.proxy.ProxyRequest.prototype.setContext = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


proto.proxy.ProxyRequest.prototype.clearContext = function() {
  this.setContext(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.proxy.ProxyRequest.prototype.hasContext = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional bytes Event = 2;
 * @return {string}
 */
proto.proxy.ProxyRequest.prototype.getEvent = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * optional bytes Event = 2;
 * This is a type-conversion wrapper around `getEvent()`
 * @return {string}
 */
proto.proxy.ProxyRequest.prototype.getEvent_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getEvent()));
};


/**
 * optional bytes Event = 2;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getEvent()`
 * @return {!Uint8Array}
 */
proto.proxy.ProxyRequest.prototype.getEvent_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getEvent()));
};


/** @param {!(string|Uint8Array)} value */
proto.proxy.ProxyRequest.prototype.setEvent = function(value) {
  jspb.Message.setField(this, 2, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.proxy.ProxyResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.proxy.ProxyResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.proxy.ProxyResponse.displayName = 'proto.proxy.ProxyResponse';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.proxy.ProxyResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.proxy.ProxyResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.proxy.ProxyResponse} msg The msg instance to transform.
 * @return {!Object}
 */
proto.proxy.ProxyResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    body: msg.getBody_asB64()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.proxy.ProxyResponse}
 */
proto.proxy.ProxyResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.proxy.ProxyResponse;
  return proto.proxy.ProxyResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.proxy.ProxyResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.proxy.ProxyResponse}
 */
proto.proxy.ProxyResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setBody(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.proxy.ProxyResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.proxy.ProxyResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.proxy.ProxyResponse} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.proxy.ProxyResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getBody_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      1,
      f
    );
  }
};


/**
 * optional bytes Body = 1;
 * @return {string}
 */
proto.proxy.ProxyResponse.prototype.getBody = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * optional bytes Body = 1;
 * This is a type-conversion wrapper around `getBody()`
 * @return {string}
 */
proto.proxy.ProxyResponse.prototype.getBody_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getBody()));
};


/**
 * optional bytes Body = 1;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getBody()`
 * @return {!Uint8Array}
 */
proto.proxy.ProxyResponse.prototype.getBody_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getBody()));
};


/** @param {!(string|Uint8Array)} value */
proto.proxy.ProxyResponse.prototype.setBody = function(value) {
  jspb.Message.setField(this, 1, value);
};


goog.object.extend(exports, proto.proxy);
