# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proxy.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proxy.proto',
  package='proxy',
  syntax='proto3',
  serialized_pb=_b('\n\x0bproxy.proto\x12\x05proxy\"P\n\x0f\x43ognitoIdentity\x12\x1b\n\x13\x63ognito_identity_id\x18\x01 \x01(\t\x12 \n\x18\x63ognito_identity_pool_id\x18\x02 \x01(\t\"\xed\x01\n\rLambdaContext\x12\x15\n\rfunction_name\x18\x01 \x01(\t\x12\x18\n\x10\x66unction_version\x18\x02 \x01(\t\x12\x1c\n\x14invoked_function_arn\x18\x03 \x01(\t\x12\x1a\n\x12memory_limit_in_mb\x18\x04 \x01(\t\x12\x16\n\x0e\x61ws_request_id\x18\x05 \x01(\t\x12\x16\n\x0elog_group_name\x18\x06 \x01(\t\x12\x17\n\x0flog_stream_name\x18\x07 \x01(\t\x12(\n\x08identity\x18\x08 \x01(\x0b\x32\x16.proxy.CognitoIdentity\"D\n\x0cProxyRequest\x12%\n\x07\x63ontext\x18\x01 \x01(\x0b\x32\x14.proxy.LambdaContext\x12\r\n\x05\x65vent\x18\x02 \x01(\x0c\"\x1d\n\rProxyResponse\x12\x0c\n\x04\x62ody\x18\x01 \x01(\x0c\x62\x06proto3')
)




_COGNITOIDENTITY = _descriptor.Descriptor(
  name='CognitoIdentity',
  full_name='proxy.CognitoIdentity',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cognito_identity_id', full_name='proxy.CognitoIdentity.cognito_identity_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cognito_identity_pool_id', full_name='proxy.CognitoIdentity.cognito_identity_pool_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=102,
)


_LAMBDACONTEXT = _descriptor.Descriptor(
  name='LambdaContext',
  full_name='proxy.LambdaContext',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='function_name', full_name='proxy.LambdaContext.function_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='function_version', full_name='proxy.LambdaContext.function_version', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='invoked_function_arn', full_name='proxy.LambdaContext.invoked_function_arn', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='memory_limit_in_mb', full_name='proxy.LambdaContext.memory_limit_in_mb', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='aws_request_id', full_name='proxy.LambdaContext.aws_request_id', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='log_group_name', full_name='proxy.LambdaContext.log_group_name', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='log_stream_name', full_name='proxy.LambdaContext.log_stream_name', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='identity', full_name='proxy.LambdaContext.identity', index=7,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=105,
  serialized_end=342,
)


_PROXYREQUEST = _descriptor.Descriptor(
  name='ProxyRequest',
  full_name='proxy.ProxyRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='context', full_name='proxy.ProxyRequest.context', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='event', full_name='proxy.ProxyRequest.event', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=344,
  serialized_end=412,
)


_PROXYRESPONSE = _descriptor.Descriptor(
  name='ProxyResponse',
  full_name='proxy.ProxyResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='body', full_name='proxy.ProxyResponse.body', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=414,
  serialized_end=443,
)

_LAMBDACONTEXT.fields_by_name['identity'].message_type = _COGNITOIDENTITY
_PROXYREQUEST.fields_by_name['context'].message_type = _LAMBDACONTEXT
DESCRIPTOR.message_types_by_name['CognitoIdentity'] = _COGNITOIDENTITY
DESCRIPTOR.message_types_by_name['LambdaContext'] = _LAMBDACONTEXT
DESCRIPTOR.message_types_by_name['ProxyRequest'] = _PROXYREQUEST
DESCRIPTOR.message_types_by_name['ProxyResponse'] = _PROXYRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CognitoIdentity = _reflection.GeneratedProtocolMessageType('CognitoIdentity', (_message.Message,), dict(
  DESCRIPTOR = _COGNITOIDENTITY,
  __module__ = 'proxy_pb2'
  # @@protoc_insertion_point(class_scope:proxy.CognitoIdentity)
  ))
_sym_db.RegisterMessage(CognitoIdentity)

LambdaContext = _reflection.GeneratedProtocolMessageType('LambdaContext', (_message.Message,), dict(
  DESCRIPTOR = _LAMBDACONTEXT,
  __module__ = 'proxy_pb2'
  # @@protoc_insertion_point(class_scope:proxy.LambdaContext)
  ))
_sym_db.RegisterMessage(LambdaContext)

ProxyRequest = _reflection.GeneratedProtocolMessageType('ProxyRequest', (_message.Message,), dict(
  DESCRIPTOR = _PROXYREQUEST,
  __module__ = 'proxy_pb2'
  # @@protoc_insertion_point(class_scope:proxy.ProxyRequest)
  ))
_sym_db.RegisterMessage(ProxyRequest)

ProxyResponse = _reflection.GeneratedProtocolMessageType('ProxyResponse', (_message.Message,), dict(
  DESCRIPTOR = _PROXYRESPONSE,
  __module__ = 'proxy_pb2'
  # @@protoc_insertion_point(class_scope:proxy.ProxyResponse)
  ))
_sym_db.RegisterMessage(ProxyResponse)


# @@protoc_insertion_point(module_scope)
