package sparta

// THIS FILE IS AUTOMATICALLY GENERATED
// DO NOT EDIT
// CREATED: 2019-08-11 20:53:40.361775 +0000 UTC

// SpartaGitHash is the commit hash of this Sparta library
const SpartaGitHash = "e94156ce02cadc61acaefca47ed9cab88640ba03"
