#!/bin/bash -x
GIT_HASH=$(git rev-parse HEAD)
DATE=`date`
cat > buildinfo.go <<- EOM
package sparta

// THIS FILE IS AUTOMATICALLY GENERATED
// DO NOT EDIT
// CREATED: $(DATE)

// SpartaGitHash is the commit hash of this Sparta library
const SpartaGitHash = "$GIT_HASH"
EOM


