package sparta

// THIS FILE IS AUTOMATICALLY GENERATED
// DO NOT EDIT
// CREATED: 2020-11-30 05:35:27.271707 +0000 UTC

// SpartaGitHash is the commit hash of this Sparta library
const SpartaGitHash = "4fe08214f3721d83a4e7937344cb3aa45f418820"
