package sparta

// THIS FILE IS AUTOMATICALLY GENERATED
// DO NOT EDIT
// CREATED: 2019-09-14 15:39:01.385244 +0000 UTC

// SpartaGitHash is the commit hash of this Sparta library
const SpartaGitHash = "bca8b07cce2819a4048ad4a8ec68e96b0a10c16e"
